vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        blob:
            uri_prefix: /blob
            upload_destination: '%kernel.project_dir%/var/storage/blob'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
                options: { chars_per_dir: 2, dirs: 2 }
